# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HH0k-zPtEizp34knS8EXEaOFzBBbEeJE
"""

# Assignment 1

li=[123,233,456,333,]
li.sort(reverse=True)
print('li in descending:',li)