# -*- coding: utf-8 -*-
"""day4 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15AZtALRZHBDSClbwhKZttxdwdns58-pI
"""

# Celsius to Fahrenheite convertor
c= int(input("Enter temperature in celsius:"))
f= ((c*9/5)+32)
print("output(temperature in fahrenheite)",f)