# -*- coding: utf-8 -*-
"""day 2 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q52QFJY1XX4J5cDNpUB8DntAUqqfV_nh
"""

# Remove all occurence of an element

def remove_values_from_list(the_list,val):
  return [value for value in the_list if value != val]

li=[2,4,5,1,2,8,2]
li= remove_values_from_list(li,2)
print(li)